name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8-buster
      - run: pip install -r requirements.txt
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
